project:
  type: website

website:
  title: "Clara Rivero Rodríguez"
  favicon: clara_logo.svg
  site-url: https://clara-rivero.github.io
  navbar:
    background: transparent
    collapse: false
    logo: clara_logo.svg
    left:
      - icon: linkedin
        href: 'https://www.linkedin.com/in/clarariverorodriguez/'
      - href: index.qmd
        text: Home
      - href: contact.qmd
        text: Contact

  sidebar:
    style: "docked"
    search: true 
    collapse-level: 2
    contents:
      - section: "Scientific illustration"
        href: illustration.qmd
        contents:
          - text: "Carpal tunnel syndrome"
            href: illustration/carpal-tunnel-syndrome.qmd
          - text: "CAR-T Therapy"
            href: illustration/car-t.qmd
      - section: "Medical writing"
        href: medical-writing.qmd
        contents:
          - text: "Diabetes · Literature review"
            href: medical-writing/diabetes-review.qmd
          - text: "Cholesterol · Practical guide"
            href: medical-writing/cholesterol-guide.qmd
          - text: "Visual health · Infographic"
            href: medical-writing/eyes-infographic.qmd
          - text: "Sleep · Copywriting"
            href: medical-writing/rest-copywriting.qmd
          - text: "CO poisoning · Article"
            href: medical-writing/co-poisoning.qmd
          - text: "Bone metabolism · Article"
            href: medical-writing/bone-metabolism.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    sidebar: true
    page-layout: full #article
    grid:
      sidebar-width: 300px
    include-in-header: google-verification.html

execute:
  freeze: auto